---
title: "climate data"
author: "Raleigh Goodwin"
date: "2/23/2021"
output: html_document
---

# Libraries
```{r}
library(tidyverse)
library(here)
library(rio)
library(psych)
library(forcats)
library(scales)
library(lme4)
library(plyr)
library(dplyr)
library(colorspace)
library(lubridate)
```

# Data
```{r}
dfc <- import(here::here("CCAMdata2008-2018.sav"))

dfc <- dfc %>% 
  mutate(yr = revalue(as.factor(year), c("1" = "2008",
                              "2" = "2010",
                              "3" = "2011",
                              "4" = "2012",
                              "5" = "2013",
                              "6" = "2014",
                              "7" = "2015",
                              "8" = "2016",
                              "9" = "2017",
                              "10" = "2018")),
         yr = as_date(yr))

```

# Plot 1

## Create smaller df
```{r}
dfc_harm <- dfc %>% 
  pivot_longer(
    cols = harm_personally:harm_plants_animals,
    names_to = "question",
    values_to = "harm"
  ) %>% 
  filter(harm != -1)

dfc_harm <- dfc_harm %>% # making these values look nice for plot
  mutate(question2 = revalue(as.factor(question), 
                             c("harm_dev_countries" = "Developing Countries",
                               "harm_future_gen" = "Future Generations",
                               "harm_personally" = "Self",
                               "harm_plants_animals" = "Plants & Animals",
                               "harm_US" = "US")),
         harm2 = revalue(as.factor(harm), 
                        c("0" = "Don't know",
                          "1" = "Not at all",
                          "2" = "Only a little",
                          "3" = "A moderate amount",
                          "4" = "A great deal")))
```

## Summary df for plot
```{r}
harm_plotL <- dfc_harm %>% 
  group_by(year, question2) %>% 
  dplyr::summarise(tot = n()) %>% 
  slice(rep(1:n(), each = 5)) %>% 
  select(tot)

harm_plotR <- dfc_harm %>%
  group_by(year, question2, harm2) %>% 
  dplyr::summarise(n = n())

harm_plot <- cbind(harm_plotL, harm_plotR) %>% 
  select(-year...3) %>% 
  mutate(year = year...1,
         perc = (n / tot) * 100) %>% 
  select(year, question2, harm2, n, tot, perc) %>% 
  mutate(question2 = factor(question2, # making sure levels are in order I want for when I facet wrap
                            levels = c("Self", "Future Generations",
                                       "US", "Developing Countries",
                                       "Plants & Animals")))
  
```

## Plot 1 Draft
```{r}
harm_plot %>% 
  ggplot(aes(year, perc, color = as.factor(harm2))) +
  geom_line(size = .75) +
  facet_wrap(~question2,
             ncol = 2) +
  # scale_x_discrete(labels = xlab) +
  labs(x = "Year", y = "Percent of Responses") +
  scale_color_viridis_d(name = "Predicted Degree of Harm",
                        option = "plasma") +
  theme_light()

# At this point I'd like to make it so that the x axis has the years displayed properly, but I'm having serious issues

harm_plot %>% 
  ggplot(aes(year, perc, color = as.factor(harm2))) +
  geom_line() +
  facet_wrap(~question2,
             ncol = 2) +
  # scale_x_discrete(labels = xlab) +
  labs(x = "Year", y = "Percent of Responses") +
  scale_color_viridis_d(name = "Predicted Degree of Harm",
                        option = "plasma") +
  scale_x_discrete(labels = xlab) +
  theme_minimal()

# That just gets rid of the x axis labels for some reason

xlab <- c(2008, 2010:2018)

harm_plot %>% 
  ggplot(aes(as.factor(year), perc, color = as.factor(harm2), group = 1)) +
  geom_line() +
  facet_wrap(~question2,
             ncol = 2) +
  # scale_x_discrete(labels = xlab) +
  labs(x = "Year", y = "Percent of Responses") +
  scale_color_viridis_d(name = "Predicted Degree of Harm",
                        option = "plasma") +
  scale_x_discrete(labels = xlab) +
  theme_minimal()

# And this just totally freaks it out

```

# Plot 2

## Create smaller df
```{r}
dfc_pol <- dfc %>% 
  pivot_longer(
    cols = reg_CO2_pollutant:reg_coal_emissions,
    names_to = "Policy",
    values_to = "Support"
  ) %>% 
  filter(Support != -1)

dfc_pol <- dfc_pol %>% # making these values look nice for plot
  mutate(Policy = revalue(as.factor(Policy), 
                             c("reg_CO2_pollutant" = "Regulate Carbon Dioxide Emissions",
                               "reg_utilities" = "Regulate Utility Energy Sources",
                               "fund_research" = "Fund Renewable Energy Research",
                               "reg_coal_emissions" = "Regulate Coal Power Plant Emissions")),
         Support = revalue(as.factor(Support), 
                        c("1" = "Strongly oppose",
                          "2" = "Somewhat oppose",
                          "3" = "Somewhat support",
                          "4" = "Strongly support")))

```

## Summary df for plot 2
```{r}
pol_plotL <- dfc_pol %>% 
  group_by(year, Policy) %>% 
  dplyr::summarise(totpol = n()) %>% 
  slice(rep(1:n(), each = 4)) %>% 
  select(totpol)

pol_plotR <- dfc_pol %>%
  group_by(year, Policy, Support) %>% 
  dplyr::summarise(npol = n())

pol_plot <- cbind(pol_plotL, pol_plotR) %>% 
  select(-year...3) %>% 
  mutate(year = year...1,
         percpol = (npol / totpol) * 100) %>% 
  select(year, Policy, Support, npol, totpol, percpol)
  
```

## Plot 2 Draft
```{r}
pol_plot %>% 
  ggplot(aes(Policy, percpol, fill = Support)) +
  geom_col(position = "dodge")

pol_plot %>% 
  ggplot(aes(Policy, percpol, fill = Support)) + #I believe you can use the mutate function along with fct_relevel to reorder the legend
  geom_col(position = "dodge") +
  coord_flip() +
  scale_fill_viridis_d(option = "plasma") +
  labs(y = "Percent of Responses",
       title = '"How much do you support or oppose..."') +
  theme_light() +
  theme(plot.title.position = "plot") +
  scale_x_discrete(labels = c("Regulating CO2 as a pollutant",
                              "Requiring electric utilities to produce\n  at least 20% of electricity using\n renewable resources",
                              "Funding more research into\n renewable energy sources",
                              "Setting strict CO2 emission\n limits on coal-fired power plants"))

# pol_plot %>% 
#   filter(year == 10) %>% 
#   ggplot(aes(Policy, percpol, fill = Support)) +
#   geom_col(alpha = .85) +
#   coord_flip() +
#   scale_fill_viridis_d(option = "plasma") +
#   labs(y = "Percent of Responses",
#        x = NULL,
#        title = '"How much do you support or oppose..."',
#        subtitle = "Results from 2018") +
#   theme_light() +
#   theme(plot.title.position = "plot",
#         legend.position = "top",
#         legend.justification = "left",
#         legend.direction = "horizontal",
#         legend.title = element_blank()) +
#   scale_x_discrete(labels = c("Regulating CO^2 as a pollutant",
#                               "Requiring electric utilities to produce\n  at least 20% of electricity using\n renewable resources",
#                               "Funding more research into\n renewable energy sources",
#                               "Setting strict CO^2 emission\n limits on coal-fired power plants")) +
#   scale_y_continuous(labels = scales::percent_format(scale = 1))
# 
# pol_plot %>% 
#   filter(year == 10) %>% 
#   ggplot(aes(Policy, percpol, fill = Support)) +
#   geom_col(alpha = .85) +
#   coord_flip() +
#   scale_fill_viridis_d(option = "plasma") +
#   labs(y = "Percent of Responses",
#        x = NULL,
#        title = '"How much do you support or oppose..."',
#        subtitle = "Results from 2018\n\n\n") +
#   theme_light() +
#   theme(plot.title.position = "plot",
#         legend.position = c(0,1),
#         legend.justification = c(.12,0),
#         legend.direction = "horizontal",
#         legend.title = element_blank()) +
#   scale_x_discrete(labels = c("Regulating CO^2 as a pollutant",
#                               "Requiring electric utilities to produce\n  at least 20% of electricity using\n renewable resources",
#                               "Funding more research into\n renewable energy sources",
#                               "Setting strict CO^2 emission\n limits on coal-fired power plants")) +
#   scale_y_continuous(labels = scales::percent_format(scale = 1))

# pol_plot %>% 
#   filter(year == 10) %>% 
#   ggplot(aes(Policy, percpol, fill = forcats::fct_rev(Support))) +
#   geom_col(alpha = .85) +
#   coord_flip() +
#   scale_fill_viridis_d(option = "plasma",
#                        guide = guide_legend(reverse = T)) +
#   labs(y = "Percent of Responses",
#        x = NULL,
#        title = '"How much do you support or oppose..."',
#        subtitle = "Results from 2018\n\n\n") +
#   theme_light() +
#   theme(plot.title.position = "plot",
#         legend.position = c(0,1),
#         legend.justification = c(.375,0),
#         legend.direction = "horizontal",
#         legend.title = element_blank()) +
#   scale_x_discrete(labels = c("Regulating CO^2 as a pollutant",
#                               "Requiring electric utilities to produce\n  at least 20% of electricity using\n renewable resources",
#                               "Funding more research into\n renewable energy sources",
#                               "Setting strict CO^2 emission\n limits on coal-fired power plants")) +
#   scale_y_continuous(labels = scales::percent_format(scale = 1))

# 
# labz <- c("Regulating CO<sup>2</sup> as a pollutant",
#           "Requiring electric utilities to produce\n  at least 20% of electricity using\n renewable resources",
#           "Funding more research into\n renewable energy sources",
#           "Setting strict CO^2 emission\n limits on coal-fired power plants")
# 
# pol_plot %>% 
#   filter(year == 10) %>% 
#   ggplot(aes(Policy, percpol, fill = Support)) +
#   geom_col(alpha = .85) +
#   coord_flip() +
#   scale_fill_viridis_d(option = "plasma",
#                        guide = guide_legend(reverse = T)) +
#   labs(y = "Percent of Responses",
#        x = NULL,
#        title = '"How much do you support or oppose..."',
#        subtitle = "Results from 2018\n\n\n") +
#   scale_x_discrete(labels = labz) +
#   scale_y_continuous(labels = scales::percent_format(scale = 1)) +
#   theme_light() +
#   theme(plot.title.position = "plot",
#         legend.position = c(0,1),
#         legend.justification = c(.375,0),
#         legend.direction = "horizontal",
#         legend.title = element_blank(),
#         axis.text.x = element_markdown())

```

# Plot 3

```{r}
dfc_voter <- dfc %>% 
  filter(registered_voter != 5 & party_w_leaners != -1 & wave > 6) %>% 
  mutate(registered_voter = factor(registered_voter,
                                   levels = c("1", "2", "3", "4")),
         party_w_leaners = as.factor(party_w_leaners)) %>% 
  na.omit()
  

voter <- lm(data = dfc_voter, formula = worry ~ party_w_leaners * registered_voter)

summary(voter)

dfc_voter %>% 
  dplyr::group_by(party_w_leaners, registered_voter) %>% 
  dplyr::summarize(mean_worry = mean(worry)) %>% 
  ggplot(aes(x = party_w_leaners, mean_worry, fill = as.factor(registered_voter))) +
  geom_col(position = "dodge")

dfc_voter %>% 
  dplyr::group_by(party_w_leaners, registered_voter) %>% 
  dplyr::summarize(mean_worry = mean(worry),
                   n = n(),
                   se = (sd(worry)/sqrt(n))) %>% 
  ggplot(aes(x = party_w_leaners, mean_worry, fill = as.factor(registered_voter))) +
  geom_col(position = "dodge") +
  geom_errorbar(aes(ymin = mean_worry - se, ymax = mean_worry + se),
                width = .2,
                position = position_dodge(.9)) +
  scale_fill_viridis_d(option = "plasma",
                       name = "Registered Voter",
                       labels = c("Yes", "No", "Don't know")) +
  scale_x_discrete(labels = c("Republican", "Democrat", "Independent/Other", "No party/Apolitical")) +
  scale_y_continuous(labels = c("Not at all worried", "Not very worried", "Somewhat worried", "Very worried"),
                     breaks = 1:4, limits = c(0, 4)) +
  labs(y = "Average Worry", x = "Political Leanings",
       title = '"How worried are you about global warming?"') +
  theme_light() +
  theme(plot.title.position = "plot")
  
```

```{r}
dfc_voter2 <- dfc %>% 
  filter(registered_voter != 5 & ideology != -1 & wave > 6) %>% 
  mutate(registered_voter = factor(registered_voter,
                                   levels = c("1", "2", "3", "4"))) %>% 
  na.omit()

voter2 <- lm(data = dfc_voter2, formula = worry ~ ideology * registered_voter)
summary(voter2)

dfc_voter2 %>% 
  dplyr::group_by(registered_voter) %>% 
  dplyr::summarize(mean_worry = mean(worry),
                   n = n(),
                   se = (sd(worry)/sqrt(n))) %>% 
  ggplot(aes(x = party_w_leaners, mean_worry, fill = as.factor(registered_voter))) +
  geom_col(position = "dodge") +
  geom_errorbar(aes(ymin = mean_worry - se, ymax = mean_worry + se),
                width = .2,
                position = position_dodge(.9)) +
  scale_fill_viridis_d(option = "plasma",
                       name = "Registered Voter",
                       labels = c("Yes", "No", "Don't know")) +
  scale_x_discrete(labels = c("Republican", "Democrat", "Independent/Other", "No party/Apolitical")) +
  scale_y_continuous(labels = c("Not at all worried", "Not very worried", "Somewhat worried", "Very worried"),
                     breaks = 1:4, limits = c(0, 4)) +
  labs(y = "Average Worry", x = "Political Leanings",
       title = '"How worried are you about global warming?"') +
  theme_light() +
  theme(plot.title.position = "plot")
```

