---
title: "Final Project Dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: united
    social: menu
    source_code: https://raleighgoodwin.github.io/EDLD-final-project/
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)
```

Page 1 {data-icon="fa-code-branch"}
==========

Column {.tabset data-width=350}
-----------------------------------------------------------------------

### Chart 1

```{r}
plot1 <- mtcars %>% 
  ggplot(aes(wt, mpg, col=as_factor(cyl))) +
  geom_point() + 
  facet_grid(~cyl)

renderPlotly(plot1)
```


### Chart 2

```{r}
table1 <- mtcars
renderDataTable(table1)
```

Column {.tabset data-width=350}
-----------------------------------------------------------------------

### Chart 3

```{r}
mtcars %>% 
  ggplot(aes(wt, mpg, col=as_factor(cyl))) +
  geom_point() + 
  facet_grid(~cyl)
```

### Chart 4

```{r}
mtcars %>% 
  ggplot(aes(wt, mpg, col=as_factor(cyl))) +
  geom_point() + 
  facet_grid(~cyl)
```

Page 2
==========

Column {data-width=700}
-----------------------------------------------------------------------

### Chart 1

```{r}
mtcars %>% 
  ggplot(aes(wt, mpg, col=as_factor(cyl))) +
  geom_point() + 
  facet_grid(~cyl)
```

### Chart 2

```{r}
mtcars %>% 
  ggplot(aes(wt, mpg, col=as_factor(cyl))) +
  geom_point() + 
  facet_grid(~cyl)
```

